export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_REGISTERED_SUCCESS = 'USER_REGISTERED_SUCCESS';
export const USER_REGISTERED_FAILURE = 'USER_REGISTERED_FAILURE';
export const CLEAR_ALL_ERRORS = 'CLEAR_ALL_ERRORS';