export const VIDEO_ITEMS_SAVE_SUCCESS = 'VIDEO_ITEMS_SAVE_SUCCESS';
export const VIDEO_ITEMS_SAVE_FAILED = 'VIDEO_ITEMS_SAVE_FAILED';
export const VIDEO_ITEMS_UNSAVE_SUCCESS = 'VIDEO_ITEMS_UNSAVE_SUCCESS';
export const VIDEO_ITEMS_UNSAVE_FAILED = 'VIDEO_ITEMS_UNSAVE_FAILED';
