export const GET_GITHUB_DATA_SUCCESS = 'GET_GITHUB_DATA_SUCCESS';
export const GET_GITHUB_DATA_FAILURE = 'GET_GITHUB_DATA_FAILURE';
export const GET_YOUTUBE_DATA_SUCCESS = 'GET_YOUTUBE_DATA_SUCCESS';
export const GET_YOUTUBE_DATA_FAILURE = 'GET_YOUTUBE_DATA_FAILURE';
export const GET_NPM_DATA_FAILURE = 'GET_NPM_DATA_FAILURE';
export const GET_NPM_DATA_SUCCESS = 'GET_NPM_DATA_SUCCESS';