export const GET_GITHUB_DATA_SUCCESS = 'GET_GITHUB_DATA_SUCCESS';
export const GET_GITHUB_DATA_FAILURE = 'GET_GITHUB_DATA_FAILURE';
export const GET_YOUTUBE_DATA_SUCCESS = 'GET_YOUTUBE_DATA_SUCCESS';
export const GET_YOUTUBE_DATA_FAILURE = 'GET_YOUTUBE_DATA_FAILURE';
export const PROFILE_DATA_RECEIVED = 'PROFILE_DATA_RECEIVED';
export const PROFILE_DATA_FAILED = 'PROFILE_DATA_FAILED';